
[workspace]
resolver = "3"
members = ["crates/oats", "crates/runtime"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
incremental = false

