name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 18
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-18 llvm-18-dev clang-18 libclang-18-dev

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Expose LLVM env
        run: |
          echo "LLVM_CONFIG=/usr/bin/llvm-config-18" >> $GITHUB_ENV
          echo "LLVM_DIR=/usr/lib/llvm-18" >> $GITHUB_ENV

      - name: Build workspace (all targets)
        run: cargo build --workspace --all-targets --verbose

      - name: Run tests
        run: cargo test --workspace --verbose

      - name: Run clippy
        run: |
          rustup component add clippy || true
          cargo clippy --all-targets -- -D warnings

      - name: Build one example (produce artifact)
        run: |
          # Build an example using the oats AOT driver to produce native artifact(s)
          OATS_OUT_DIR=./aot_out
          cargo run -p oats --bin aot_run -- examples/cycle_reclaim.oats || true

      - name: Upload built examples/artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aot-examples
          path: aot_out/
